<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Zend Framework Bootcamp</title>
    </head>
    <body>
        <?php if ($this->flashMessages): ?>
        <div id="flashMessages">
    	    <ul>
                <?php foreach ($this->flashMessages as $message): ?>
    			<li><?php echo $message; ?></li>
    			<?php endforeach; ?>
    		</ul>
    	</div>
    	<?php endif; ?>
    	
    	<div id="Content">
    	    <?php echo $this->layout()->content; ?>
    	</div>
    </body>
</html>